import type { Metadata } from "next";
import Link from "next/link";
import { getAdminHealth } from "@/lib/data";
import { LocalDateTime } from "@/components/local-date-time";

export const metadata: Metadata={title:"Ingestion health"}; export const dynamic="force-dynamic";
const stamp=(value:unknown)=>value?<LocalDateTime value={value as string | Date}/>:"Never";
export default async function AdminPage(){const data=await getAdminHealth();return <div className="shell"><header className="page-head"><span className="eyebrow">{"// Protected operations console"}</span><h1>Ingestion health</h1><p>Collector status, raw-response audit trail, reconciliation diagnostics, schema changes, and backfill progress.</p></header>
  <dl className="metrics"><div className="metric"><dt>Last successful collection</dt><dd style={{fontSize:18}}>{stamp(data.summary.last_success)}</dd><small>raw and normalized</small></div><div className="metric"><dt>Collector heartbeat</dt><dd style={{fontSize:18}}>{stamp(data.worker?.heartbeat_at)}</dd><small>{String(data.worker?.metadata?.status??"not started")} · {String(data.worker?.metadata?.runStatus??"no completed run")}</small></div><div className="metric"><dt>Raw responses</dt><dd>{Number(data.summary.raw_responses).toLocaleString()}</dd><small>never intentionally deleted</small></div><div className="metric"><dt>Open parser errors</dt><dd className={data.summary.parser_errors?"health-bad":"health-good"}>{data.summary.parser_errors}</dd><small>{data.summary.historical_parser_errors} historical failures retained</small></div><div className="metric"><dt>Revisions</dt><dd>{data.tables.revisions}</dd><small>upstream changes preserved</small></div></dl>
  <section className="section"><div className="panel"><div className="panel-header"><h3>Endpoints</h3><span className="chip">Polling schedule</span></div><div className="data-scroll"><table className="data-table"><thead><tr><th>Source</th><th>Endpoint</th><th>Last attempt</th><th>Status</th><th>Response</th><th>Schedule</th></tr></thead><tbody>{data.sources.map((row)=><tr key={row.source_key}><td>{row.source_key}</td><td><code>{row.endpoint}</code></td><td>{stamp(row.last_attempt_at)}</td><td><span className={`status ${row.processing_status==="PROCESSED"?"kill":"error"}`}>{row.http_status??"—"} {row.processing_status??"pending"}</span></td><td>{row.duration_ms??"—"} ms</td><td>{row.poll_interval_seconds}s</td></tr>)}</tbody></table></div></div></section>
  <section className="section"><div className="dashboard-grid"><div className="panel"><div className="panel-header"><h3>Database totals</h3><span className="chip">Normalized</span></div>{Object.entries(data.tables).map(([key,value])=><div className="rank-row" key={key}><span className="rank">›</span><span>{key.replaceAll("_"," ")}</span><span className="credits">{Number(value).toLocaleString()}</span></div>)}</div><div className="panel"><div className="panel-header"><h3>Backfill checkpoints</h3><span className="chip">Resumable</span></div>{data.checkpoints.length?data.checkpoints.map((row)=><div className="rank-row" key={row.job_key}><span className={`status ${row.status==="SUCCEEDED"?"kill":""}`}>{row.status}</span><span>{row.job_key}</span><span>{stamp(row.updated_at)}</span></div>):<div className="empty">Backfill has not run.</div>}</div></div></section>
  <section className="section"><div className="panel"><div className="panel-header"><h3>Recent ingestion runs</h3><span className="chip">Structured audit</span></div><div className="data-scroll"><table className="data-table"><thead><tr><th>Run</th><th>Type</th><th>Started</th><th>Status</th><th>Requests</th><th>Inserted</th><th>Unchanged</th><th>Revised</th><th>Duplicates blocked</th><th>Errors</th></tr></thead><tbody>{data.runs.map((row)=><tr key={row.id}><td><code>{String(row.id).slice(0,8)}</code></td><td>{row.run_type}</td><td>{stamp(row.started_at)}</td><td><span className={`status ${row.status==="SUCCEEDED"?"kill":row.status==="FAILED"?"error":""}`}>{row.status}</span></td><td>{row.requests}</td><td>{row.inserted}</td><td>{row.unchanged}</td><td>{row.revised}</td><td>{row.duplicates_prevented}</td><td>{row.errors}</td></tr>)}</tbody></table></div></div></section>
  <section className="section"><div className="dashboard-grid"><div className="panel"><div className="panel-header"><h3>Data quality</h3><span className={`status ${data.quality.length?"error":"kill"}`}>{data.quality.length} open</span></div>{data.quality.length?data.quality.map((row)=><div className="notice" key={row.id}><b>{row.event_type}</b><br/>{stamp(row.detected_at)}<pre>{JSON.stringify(row.details,null,2)}</pre></div>):<div className="empty">No open integrity events.</div>}</div><div className="panel"><div className="panel-header"><h3>Failed jobs</h3><span className={`status ${data.errors.length?"error":"kill"}`}>{data.errors.length} open</span></div>{data.errors.length?data.errors.map((row)=><div className="notice" key={row.id}><b>{row.error_code}</b><br/>{row.message}</div>):<div className="empty">No unresolved ingestion errors.</div>}</div></div></section>
  <section className="section"><div className="panel"><div className="panel-header"><h3>Raw payload audit</h3><span className="chip">Latest 20</span></div><RawLinks/></div></section>
  </div>}

async function RawLinks(){const {pool}=await import("@/lib/db/client");const result=await pool.query("SELECT id,endpoint,http_status,processing_status,response_received_at,payload_hash FROM api_ingestions ORDER BY response_received_at DESC LIMIT 20");return <div className="data-scroll"><table className="data-table"><thead><tr><th>Received</th><th>Endpoint</th><th>Status</th><th>SHA-256</th></tr></thead><tbody>{result.rows.map((row)=><tr key={row.id}><td>{stamp(row.response_received_at)}</td><td><Link href={`/admin/ingestion/raw/${row.id}`}>{row.endpoint}</Link></td><td>{row.http_status} {row.processing_status}</td><td><code>{String(row.payload_hash??"—").slice(0,18)}…</code></td></tr>)}</tbody></table></div>}
